= Software Challenge Endbenutzer-Dokumentation
Sven Koschnicke <svk@informatik.uni-kiel.de>
2015-01-06
:imagesdir: ./images
:toc: right
:toc-title: Inhalt
:source-highlighter: pygments
:icons: font

Ziel dieser Dokumentation ist es, alle Informationen über die
Software-Challenge an einer Stelle zu bündeln. Hier können sich Lehrer
und Kursleiter über den Zweck der Software-Challenge informieren. Für
die teilnehmenden Teams ist hier alles dokumentiert, was für den
Ablauf des Wettbewerbes benötigt wird.

Wir freuen uns über sämtliche Verbesserungsvorschläge. Die
Dokumentation kann
https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs[direkt auf
GitHub editiert] werden, einzige Voraussetzung ist eine kostenlose
Registrierung bei GitHub. Ist man angemeldet, kann man ein Dokument
auswählen (ein guter Startpunkt ist die Datei
https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs/blob/master/index.adoc[index.adoc]
welche Verweise auf alle Sektionen der Dokumentation enthält) und dann
auf den Stift oben rechts klicken. Alternativ auch gern eine E-Mail an
svk@informatik.uni-kiel.de.

include::allgemein/die-software-challenge.adoc[]

include::software/server.adoc[]

include::software/client.adoc[]

include::entwicklung/installation-von-java.adoc[]

include::entwicklung/einrichtung-der-entwicklungsumgebung.adoc[]

include::entwicklung/bedienung-von-eclipse.adoc[]

include::entwicklung/simpleclient-erweitern.adoc[]

include::entwicklung/client-abgabefertig-machen.adoc[]

include::entwicklung/erste-schritte.adoc[]

include::entwicklung/einfuehrung-oop.adoc[]

include::entwicklung/sauberer-programmierstil.adoc[]

include::entwicklung/eine-idee-implementieren.adoc[]

include::entwicklung/weiterfuehrende-literatur.adoc[]

include::software/schnittstelle.adoc[]

include::software/einfuehrung-xml.adoc[]

include::allgemein/wettkampfmodalitaeten.adoc[]

include::software/das-wettkampfsystem.adoc[]
