= Software Challenge Endbenutzer-Dokumentation
Sven Koschnicke <svk@informatik.uni-kiel.de>
2015-01-06
:imagesdir: ./images
:toc: right
:toc-title: Inhalt
:source-highlighter: pygments
:icons: font

Ziel dieser Dokumentation ist es, alle Informationen über die
Software-Challenge an einer Stelle zu bündeln. Hier können sich Lehrer
und Kursleiter über den Zweck der Software-Challenge informieren. Für
die teilnehmenden Teams ist hier alles dokumentiert, was für den
Ablauf des Wettbewerbes benötigt wird.

Wir freuen uns über sämtliche Verbesserungsvorschläge. Die
Dokumentation kann
https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs[direkt auf
GitHub editiert] werden, einzige Voraussetzung ist eine kostenlose
Registrierung bei GitHub. Ist man angemeldet, kann man ein Dokument
auswählen (ein guter Startpunkt ist die Datei
https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs/blob/master/index.asciidoc[index.asciidoc]
welche Verweise auf alle Sektionen der Dokumentation enthält) und dann
auf den Stift oben rechts klicken. Alternativ auch gern eine E-Mail an
svk@informatik.uni-kiel.de.

include::allgemein/die-software-challenge.asciidoc[]

include::software/server.asciidoc[]

include::software/client.asciidoc[]

include::entwicklung/installation-von-java.asciidoc[]

include::entwicklung/einrichtung-der-entwicklungsumgebung.asciidoc[]

include::entwicklung/bedienung-von-eclipse.asciidoc[]

include::entwicklung/simpleclient-erweitern.asciidoc[]

include::entwicklung/client-abgabefertig-machen.asciidoc[]

include::entwicklung/erste-schritte.asciidoc[]

include::entwicklung/einfuehrung-oop.asciidoc[]

include::entwicklung/sauberer-programmierstil.asciidoc[]

include::entwicklung/eine-idee-implementieren.asciidoc[]

include::entwicklung/weiterfuehrende-literatur.asciidoc[]

include::software/schnittstelle.asciidoc[]

include::software/einfuehrung-xml.asciidoc[]

include::allgemein/wettkampfmodalitaeten.asciidoc[]

include::software/das-wettkampfsystem.asciidoc[]
