= Software Challenge Endbenutzer-Dokumentation-Dokumentation
Sven Koschnicke <svk@informatik.uni-kiel.de>
2015-01-06
:toc:
:toc-title: Inhalt

In diesem Repository befindet sich die Endbenutzer-Dokumentation fuer
die Software Challenge. Zielgruppe sind Schueler und Leherer, die an
der Software Challenge teilnehmen.

== Konventionen

* Die Hauptdatei ist `index.asciidoc` im Wurzelverzeichnis. Alle
  anderen Dateien werden per `include`-Anweisung in die Hauptdatei
  eingebungen.
* Dateinamen und Verzeichnisnahmen sollten nur die Zeichen `a` bis `z`
  sowie Bindestriche (`-`) enthalten.
* Sprache fuer Dateinamen, Verzeichnisnamen sowie Inhalt ist
  Deutsch. Sprache fuer Attribute und sonstige Interna ist Englisch.
* Als Endung fuer Asciidoc wird `.asciidoc` benutzt.
* Es wird des ATX-Format fuer Ueberschriften verwendet (also `=`,
  `==`, `===` etc.)

== Übersetzung

Um alles in HTML zu Übersetzen, sollte `asciidoctor` verwendet werden:

....
asciidoctor -D out index.asciidoc
....

Hierzu werden die beiden Ruby-Gems `asciidoctor` und `pygments.rb`
(für Syntax-Highlighting der Quellcodes) benötigt.

== Quickstart

* http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]
* http://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide]
* http://asciidoctor.org/docs/user-manual/[AsciiDoctor User Manual]
* http://asciidoctor.org/docs/asciidoc-recommended-practices/[AsciiDoc Style Guide]

Es werden häufig Links zu anderen Teilen des Dokumentes genutzt (die Dokumentation ist ein einzelnes großes Dokument). Diese haben die Syntax `<<Sektionslabel,anzuzeigender Linktext>>`. Wobei Sektionslabel über allen Überschriften stehen und die Syntax `[[labelname]]` haben.