== Felder
Es gibt acht verschiedene Spielfelder:

=== Startfeld
Das Startfeld darf nur verlassen werden. Es ist nicht erlaubt das Startfeld erneut zu betreten, sollte es einmal verlassen werden. Auf ihm starten beide Spieler

=== Karottenfeld
Ein Karottenfeld darf durch jede Bewegungsaktion (Vorwärtszug, Karten) betreten werden. Nur auf ihm darf ein Karotten tauschen Zug stattfinden (die Karotten tauschen Karte darf hier nicht benutzt werden).

=== Hasenfeld
Darf nur betreten werden, wenn eine Karte gespielt werden kann. Sollte sich ein Spieler am Ende seines Zuges auf einem Hasenfeld befinden, muss dieses im nächsten Zug (wenn möglich) verlassen werden (es ist erlaubt das Hasenfeld zu verlassen und dann durch nutzen von Karten wieder zu betreten).

=== Salatfeld
Darf nur betreten werden, der Spieler mindestens einen Salat besitzt. In dem Zug nach dem Betreten muss ein Salat gefressen werden. Nur auf einem Salatfeld darf ein Salat gefressen werden (außer natürlich durch die Karte Salat fressen). Das Salatfeld muss verlassen werden (wenn möglich) sobald ein Salat gegessen wurde (es ist innerhalb des Spiels trotzdem durch Rückzüge oder Karten möglich auf demselben Salatfeld mehrere Salate zu essen).

=== Igelfeld
Darf nur durch einen Rückzug betreten werden. Muss (wenn möglich) im nächsten Zug wieder verlassen werden.

=== Position-1 Feld
Das Position 1 Feld darf uneingeschränkt betreten werden. Sollte sich ein Spieler am Anfang seines Zuges auf diesem Feld befinden und an erster Stelle stehen, so erhält er zehn Karotten.

=== Position-2 Feld
Das Position 2 Feld darf uneingeschränkt betreten werden. Sollte sich ein Spieler am Anfang seines Zuges auf diesem Feld befinden und an zweiter Stelle stehen, so erhält er 30 Karotten.

=== Zielfeld
Das Zielfeld darf nur betreten werden, wenn der Spieler höchstens zehn Karotten und keine Salate besitzt.

