= Modifizierte Spielregeln Hase und Igel Software Challenge 2018
Sven Koschnicke <svk@informatik.uni-kiel.de>
:imagesdir: ./../images
:toc: right
:toc-title: Inhalt
:source-highlighter: pygments
:icons: font

Ziel dieser Dokumentation ist es, die Spielregeln der Softwarechallenge festzuhalten.

Wir freuen uns über sämtliche Verbesserungsvorschläge. Die
Dokumentation kann
https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs[direkt auf
GitHub editiert] werden, einzige Voraussetzung ist eine kostenlose
Registrierung bei GitHub. Ist man angemeldet, kann man ein Dokument
auswählen (ein guter Startpunkt ist die Datei
https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs/blob/master/index.adoc[index.adoc]
welche Verweise auf alle Sektionen der Dokumentation enthält) und dann
auf den Stift oben rechts klicken. Alternativ auch gern eine E-Mail an
svk@informatik.uni-kiel.de.


Die Nutzung des Spielkonzeptes "Hase und Igel" (Name, Spielregeln und Grafik) erfolgt mit
freundlicher Genehmigung der Ravensburger Spieleverlag GmbH.
Das Spielfeld der Version 2008 vom Ravensburger Spieleverlag wird folgendermaßen modifiziert:
1. Die Igel- und Salatfelder werden so angeordnet wie im Original. Die Felder zwischen 2 Igelfeldern
mit Ausnahme der Salatfelder werden zufällig permutiert.
2. Die Zahlenfelder 3 und 4 werden durch Möhrenfelder ersetzt.
3. Das Zahlenfeld 1/5/6 wird durch das Zahlenfeld 1 ersetzt.

include::spielbeginn.adoc[]
include::zuege.adoc[]
include::felder.adoc[]
include::spielende.adoc[]
include::beispiel.adoc[]



