== Zugmöglichkeiten

Ein Spieler kann folgende Züge machen:

=== Vorwärtszug
Durch einen Vorwärtszug bewegt sich der Spieler um die entsprechende Zahl von Feldern nach vorne (mindestens 1). Dabei werden Karotten entsprechend der Rennkarte verbraucht. 
Wenn ein Spieler sich auf dem Startfeld befindet muss ein Vorwärtszug gemacht werden.
Wenn ein Spieler sich auf einem Startfeld befindet und den letzten Zug einen Salat gefressen hat, muss ein Bewegungszug gemacht werden (Vorwärtszug oder Rückwärtszug).
Ein Spieler darf nicht auf ein Feld ziehen, dass bereits durch den Gegner besetzt ist, außer es handelt sich um das Zielfeld.
Durch eine Vorwärtszug dürfen alle Felder außer das Igelfeld direkt betreten werden.
Es ist nicht erlaubt das Zielfeld zu betreten, wenn die Siegbedingungen (höchstens 10 Karotten und 0 Salate) nicht erfüllt sind.
Wenn durch einen Vorwärtszug ein Hasenfeld betreten wird, muss danach eine Karte ausgespielt werden.

=== Rückwärtszug
Durch einen Rückwärtszug zieht der Spieler zu dem vorherigen Igelfeld, sollte dies nicht besetzt sein.
ist das vorherige Igelfeld besetzt, darf kein Rückzug gemacht werden.
Durch einen Rückzug werden 10 mal zurückgezogene Felder viele Karotten aufgenommen.

=== Karte ausspielen
Eine Karte muss ausgespielt werden, wenn ein Hasenfeld neu betreten wird. Dies ist entweder durch eine Vorwärtszug oder das Ausspielen einer Karte möglich.
Sollte es nicht möglich sein eine Karte auszuspielen ist das Betreten eines Hasenfeldes nicht erlaubt.
Ein Spieler hat zu Beginn folgende Karten:

==== Salat fressen (Karte)
Es wird ein Salat vom Spieler entfernt, je nach Position des Spielers (Erster/Zweiter) erhält der Spieler Karotten (10/30).
Diese Karte darf nur eingesetzt werden, wenn der Spieler mehr als einen Salat hat. Im dem nächsten Zug muss das betretene Hasenfeld verlassen werden.

==== Karotten tauschen (Karte)
Der Spieler darf 20 Karotten abgeben oder aufnehmen oder nichts tun. Es darf der Spieler nicht mehr Karotten abgeben als er besitzt. Im dem nächsten Zug muss das betretene Hasenfeld verlassen werden.

==== Rücke eine Position vor
Kann nur ausgespielt werden, wenn der Spieler sich an zweiter Position befindet. Der Spieler rückt auf das Feld vor dem gegnerischen Spieler vor. Dies ist nicht erlaubt, sollte es sich bei dem so betretenen Feld um ein Igelfeld handeln oder sollte der gegnerische Spieler sich im Ziel befinden. Es ist außerdem nicht erlaubt, so ein Salatfeld zu betreten ohne mindestens einen Salat zu besitzen. Es kann so das Ziel erreicht werden, wenn die Siegbedingungen erfüllt sind.

==== Falle eine Position zurück
Kann nur ausgespielt werden, wenn der Spieler sich an erster Position befindet. Der Spieler fällt auf das Feld hinter dem gegnerischen Spieler zurück. Dies ist nicht erlaubt, sollte es sich bei dem so betretenen Feld um ein Igelfeld handeln oder sollte der gegnerische Spieler sich auf dem Startfeld befinden. Es ist außerdem nicht erlaubt, so ein Salatfeld zu betreten ohne mindestens einen Salat zu besitzen.

=== Karotten tauschen (Aktion)
Kann nur ausgeführt werden, wenn sich der Spieler auf einem Karottenfeld befindet. Es können entweder zehn Karotten abgegeben werden (dabei muss der Spieler mindestens zehn Karotten besitzen)
oder 10 Karotten aufgenommen werden.

=== Salat fressen (Aktion)
Wenn sich der Spieler auf einem Salatfeld befindet und er in seiner letzten Aktion, die kein Aussetzzug war, keinen Salat gefressen hat, darf er einen Salat fressen.
Der Spieler verliert einen Salat (dies ist immer möglich, da ein Spieler nur mit mindestens einem Salat ein Salatfeld betreten kann) und erhält je nach Position (Erster/Zweiter) Karotten (10/30).

=== Aussetzen
Es Spieler darf nur Aussetzen, sollte sonst keine anderer Zug möglich sein.

=== Zusammenfassung
Ein Zug kann als entweder nur aus einem Rückzug, Salat fressen, Karotten tauschen,  Aussetzen oder einem Vorwärtszug und 0 bis 3 Karten (sollte ein Hasenfeld oder durch Karten Hasenfelder betreten werden).


