:imagesdir: images
:source-highlighter: pygments
:icons: font
:toc: left
:toc-title: Inhalt

= Ostseeschach Spielregeln der Software-Challenge 2022

ifndef::backend-pdf[link:regeln.pdf[PDF-Version dieses Dokumentes]]

include::../../allgemein/beitragen.adoc[]

== Spielaufbau

Ostseeschach ist ein Brettspiel,
das mit Figuren auf einem Schachbrett (8x8) gespielt wird.
Jeder Spieler hat acht Figuren, wobei - wie beim Schach –
die Art der Figur bestimmt, wie sie setzen kann:

Herzmuschel:: jeweils ein Feld schräg nach vorne
              (so wie ein Schach-Bauer schlagen kann)

Möwe:: kann auf ein in horizontaler oder vertikaler Richtung benachbartes Feld ziehen
       (wie ein Turm beim Schach, aber jeweils nur ein Feld weit)

Seestern:: einen Schritt nach vorne oder in eine der vier Diagonalrichtungen

Robbe:: kann zwei Schritte in eine (horizontale oder vertikale) Richtung
        und ein Feld senkrecht zu dieser Richtung springen
        (wie ein Springer beim Schach)

Die Robbe ist die mächtigste Figur,
weil sie in einem Zug weiter als ein Feld gehen kann.
Die anderen Figuren bezeichnet man daher als „Leichtfiguren“.

Jeder Spieler startet mit zwei Figuren jeder Art.
Zu Beginn des Spiels werden die roten Figuren zufällig auf der Linie 1 des Schachfeldes verteilt,
die blauen Figuren werden drehsymmetrisch dazu auf der Linie 8 aufgestellt.
Rot hat den ersten Zug.

== Spielablauf

Ziel des Spiels ist, zwei Bernsteine zu erringen.
Wer das als erster schafft, gewinnt.

Es wird abwechselnd jeweils eine Figur bewegt.
Eine Bewegung muss entweder auf einem freien Feld
oder einer gegnerischen Figur enden.
In letzterem Fall wird die Figur auf die dortige gelegt,
wodurch ein Turm entsteht.
Ein Turm zieht immer wie die Figur, die oben liegt.
Wenn eine der beiden am Schlagen beteiligten Figuren
bereits ein Turm ist,
so erhält der schlagende Spieler einen Bernstein
und alle beteiligten Figuren werden vom Feld entfernt.

Man kann ebenfalls einen Bernstein bekommen,
indem man eine der Leichtfiguren (Herzmuschel, Seestern oder Möwe)
bis zur gegnerischen Startlinie bewegt.

Es gibt also zwei Arten,
einen Bernstein zu bekommen:

- einen Turm der Höhe drei oder vier erreichen
- eine Leichtfigur zur gegnerischen Startlinie bewegen

Wenn man beide Bedingungen in einem Zug erfüllt,
erhält man zwei Bernsteine.
Die Figur, für die man einen Bernstein bekommt,
wird vom Spielfeld genommen.

== Wertung

Das Spiel endet in der Runde,
in der ein Spieler zwei Bernsteine erreicht,
spätestens jedoch nach 30 Runden.
Es gewinnt, wer mehr Bernsteine hat.

Haben beide Spieler gleich viele Bernsteine,
gewinnt der Spieler mit der Leichtfigur,
die den größten Abstand zur eigenen Startlinie hat.
Bei Gleichstand wird die jeweils darauffolgende Leichtfigur verglichen,
bis bei mindestens einem Spieler keine Leitfigur mehr übrig ist.
Wenn sich auf diese Weise keine Entscheidung ergibt,
endet das Spiel unentschieden.

In der Meisterschaftsphase und in der Champions League
ist die Anzahl der Bernsteine nachrangiges Kriterium,
also wenn zwei Teams gleich viele Siege errungen haben,
bekommt das Team mit der höheren durchschnittlichen Anzahl der Bernsteine
den besseren Tabellenplatz.
