== Der Computerspieler (Client)

Der Computerspieler ist ein Programm, dass
sich mit dem link:Der Spielleiter (Server)[Der Spielleiter (Server)]
verbindet und die gestellte Aufgabe selbstängig lösen kann. Die Aufgabe
der Schüler ist es, sich eine Strategie zu überlegen und zu
implementieren, mit der sie gegen die Clients der anderen Schulen
gewinnen können.

Der Computerspieler kann in einer beliebigen Programmiersprache
geschrieben sein, jedoch bietet das Institut für Informatik die beste
Unterstützung für Java.

Die Muster-Computerspieler können im Downloadbereich
(http://www.informatik.uni-kiel.de/software-challenge/2013/download/)
heruntergeladen werden.

*Hinweis:* Die Programme, die das Institut für Informatik zur Verfügung
stellt, sind üblicherweise in Java geschrieben. Deshalb muss auf den
ausführenden Rechnern auch das link:Installation von Java[Java 6 oder 7
SDK installiert] sein.

[[der-simpleclient]]
=== Der SimpleClient

Der SimpleClient ist ein Computerspieler, den das Institut für
Informatik ins Rennen schickt. Er stellt zwar eine korrekte Lösung der
gestellten Aufgabe dar, ist aber nicht besonders intelligent. Neben dem
eigentlichen Programm ist auch der Quellcode des SimpleClients
verfügbar. Auf diese Weise können sich die Schüler anschauen und lernen,
wie man beispielsweise die gestellte Aufgabe lösen kann. Außerdem darf
der Code um die eigene Strategie erweitert werden. Auf diese Weise
müssen die Schüler nicht den ganzen Computerspieler selbst entwickeln,
sondern können sich auf den Entwurf und die Implementierung ihrer
eigenen Strategie konzentrieren.

[[der-notsosimpleclient]]
=== Der NotSoSimpleClient

Wenn die aktuelle Saison der Software-Challenge etwas weiter
fortgeschritten ist, stellt das Institut einen stärkeren Computerspieler
zur Verfügung: den NotSoSimpleClient. Das ist ein Spieler, der eine
effizientere Strategie zur Lösung der Aufgabe als der SimpleClient
verfolgt und dadurch nicht mehr so leicht zu schlagen ist. Dieser
Spieler wird ohne den Quellcode veröffentlicht, so dass die Schüler den
NotSoSimpleClient zwar als Gegenspieler für Testspiele nehmen, jedoch
nicht den Quellcode für den eigenen Spieler weiterverwenden können.

[[weiterführende-informationen]]
=== Weiterführende Informationen

* link:Installation von Java[Installation von Java]
* link:Einrichtung der Entwicklungsumgebung (Java)[Einrichtung der
Entwicklungsumgebung (Java)]
* link:Bedienung von Eclipse[Bedienung von Eclipse]
* link:Den SimpleClient um eine eigene Strategie erweitern[Den
SimpleClient um eine eigene Strategie erweitern]
* link:Den Client abgabefertig machen[Den Client abgabefertig machen]

