[[administration]]
=== Administration

Mit einem authentifizierten Client kann man den Server steuern.

==== Verbindungsaufbau

Zuerst muss sich ein Client mit dem entsprechenden Passwort aus `server.properties` authentifizieren:

[source, xml]
----
<protocol><authenticate password="examplepassword"/>
----

Ein authentifizierter AdminClient wird benachrichtigt,
wenn sich ein Client über ein `JoinRoomRequest` verbindet:

[source,xml]
----
<joinedGameRoom roomId=ROOMID playerCount=X />
----
roomId:: eine vom Server generierte Zeichenfolge, die die Partie identifiziert
playerCount:: die Anzahl der Spieler im Raum nach dem Beitritt des neuen Spielers

==== Aktionen in einem Raum

Ein AdminClient kann sich als Observer eines Raums anmelden,
dadurch erhält er alle Nachrichten, die das Spiel betreffen:

[source,xml]
----
<observe roomId=ROOMID />
----

Ein AdminClient kann ein Spiel pausieren oder fortsetzen:

[source,xml]
----
<pause roomId=ROOMID pause="true/false" />
----

Ein AdminClient kann einen Zug in einem pausierten Spiel anfordern:

[source,xml]
----
<step roomId=ROOMID />
----

Ein AdminClient kann ein Spiel abbrechen:

[source,xml]
----
<cancel roomId=ROOMID />
----

Ein AdminClient kann ein Spiel vorbereiten:

[source,xml]
----
<prepare gameType="pluginId" pause="true">
  <slot displayName="p1" canTimeout="true" reserved="true"/>
  <slot displayName="p2" canTimeout="true" reserved="true"/>
</prepare>
----

==== Testmodus

Ein AdminClient kann den Testmodus aktivieren/deaktivieren:

[source,xml]
----
<testMode testMode="true/false" />
----
Der Server antwortet mit:

[source,xml]
----
<testing testMode="true/false" />
----

Nachdem der Testmodus aktiviert wurde
kann ein AdminClient die Punkte und Gewinnkriterien eines Spielers
jederzeit anhand des Anzeigenamens erfragen:

[source,xml]
----
<scoreForPlayer displayName="p1"/>
----
Der Server antwortet darauf mit:

[source,xml]
----
<playerScore>
  <score displayName="p1" numberOfTests="1">
    <values>
      <fragment name="Gewinner">
        <aggregation>SUM</aggregation>
        <relevantForRanking>true</relevantForRanking>
      </fragment>
      <value>2</value>
    </values>
    <values>
      <fragment name="∅ Feldnummer">
        <aggregation>AVERAGE</aggregation>
        <relevantForRanking>true</relevantForRanking>
      </fragment>
      <value>10.000000</value>
    </values>
    <values>
      <fragment name="∅ Karotten">
        <aggregation>AVERAGE</aggregation>
        <relevantForRanking>true</relevantForRanking>
      </fragment>
      <value>13.000000</value>
    </values>
  </score>
</playerScore>
----

[[servereinstellungen]]
==== Servereinstellungen

Die Servereinstellungen liegen in der `server.properties` Datei,
die zusammen mit dem Server heruntergeladen wird.
In ihr können folgende Werte konfiguriert werden:

password:: lokales Administratorpasswort (standardmäßig auf `examplepassword`)
paused:: ob ein automatisch angelegtes Spiel anfangs pausiert sein soll oder nicht (standardmäßig pausiert)
