== Spielstatus
Es folgt die Beschreibung des Spielstatus, der vor jeder Zugaufforderung an die Clients gesendet wird. Das Spielstatus-Tag ist dabei noch in einem _data_-Tag der Klasse _memento_ gewrappt:

[[memento]]
=== memento
--
* ROOM_ID Id des GameRooms
* STATUS Gamestate wie in xref:status[]
--
[source,xml]
----
<room roomId="ROOM_ID">
  <data class="memento">
    STATUS
  </data>
</room>
----

[[status]]
=== Status
--
* Z aktuelle Zugzahl
* S Spieler, der das Spiel gestartet hat (RED/BLUE)
* C Spieler, der an der Reihe ist (RED/BLUE)
* red, blue wie in xref:spieler[] definiert
* board Das Spielbrett, wie in xref:spielbrett[] definiert
* lastMove Letzter getätigter Zug (nicht in der ersten Runde), wie in xref:letzter-zug[] definiert
* condition Spielergebnis, wie in xref:spielende[] definiert; nur zum Spielende
--
[source,xml]
----
<state class="state" turn="Z" startPlayer="S" currentPlayer="C">
  red
  blue
  [board]
  [lastMove]
  [condition]
</state>
----

[[spieler]]
=== Spieler
--
* c Farbe (red/blue)
* C Farbe (RED/BLUE)
--
[source,xml]
----
<c displayName="N" color="C" />
----

[[spielbrett]]
=== Spielbrett
--
* FIELD Ein Spielfeld wie in xref:spielfeld[] definiert.
--
[source,xml]
----
<board>
  <fields>
    <field x="0" y="0" state="EMPTY" />
    ...
    FIELD
    ...
    <field x="0" y="9" state="EMPTY" />
  </fields>
  ...
  <fields>
    <field x="9" y="0" state="EMPTY" />
    ...
    FIELD
    ...
    <field x="9" y="9" state="EMPTY" />
  </fields>
</board>
----
[[spielfeld]]
=== Spielfeld
--
* X X-Koordinate
* Y Y-Koordinate
* STATE Zustand des Feldes (RED,BLUE,OBSTRUCTED,EMPTY)
--
[source,xml]
----
<field x="X" y="Y" state="STATE" />
----

[[letzter-zug]]
=== Letzter Zug
Der letzte Zug ist ein Move (siehe hierzu xref:zug[]).

[source,xml]
----
<lastMove>
  ZUG
</lastMove>
----
