== Einleitung

Wie in den letzten Jahren wird zur Client-Server Kommunikation ein XML-Protokoll genutzt.
In diesem Dokument wird die Kommunikationsschnittstelle definiert, sodass ein
komplett eigener Client geschrieben werden kann. Es wird hier nicht die
vollständige Kommunikation dokumentiert bzw. definiert, dennoch alles, womit ein
Client umgehen können muss, um spielfähig zu sein.

[[an-wen-richtet-sich]]
=== An wen richtet sich dieses Dokument?

Die Kommunikation mit dem Spielserver ist für diejenigen, die aufbauend auf dem
Simpleclient programmieren, unwichtig. Dort steht bereits ein funktionierender
Client bereit und es muss nur die Spiellogik entworfen werden. Nur wer einen
komplett eigenen Client entwerfen will, beispielsweise um die Programmiersprache
frei wählen zu können, benötigt die Definitionen.

[[hinweise]]
=== Hinweise

Falls Sie beabsichtigen sollten, diese Kommunikationsschnittstelle zu
realisieren, sei darauf hingewiesen, dass es im Verlauf des Wettbewerbes möglich
ist, dass weitere, hier noch nicht aufgeführte Elemente zur
Kommunikationsschnittstelle hinzugefügt werden. Um auch bei solchen Änderungen
sicher zu sein, dass ihr Client fehlerfrei mit dem Server kommunizieren kann,
empfehlen wir Ihnen, beim Auslesen des XML jegliche Daten zu verwerfen, die hier
nicht weiter definiert sind. Die vom Institut bereitgestellten
Programme (Server, Simpleclient) nutzen eine Bibliothek um Java-Objekte direkt
in XML zu konvertieren und umgekehrt.
Dabei werden XML-Nachrichten nicht unbedingt mit einer newline abgeschlossen.

WARNING: Die XML Dokumentation behandelt ausschließlich die Kommunikation. Falls Sie Dokumentation für den Verbindungsaufbau suchen, so finden Sie diese https://docs.software-challenge.de/_computerspieler_abgabefertig_machen.html#andere-sprache[hier].
