[[spielstatus]]
== Spielstatus

Es folgt die Beschreibung des Spielstatus, der vor jeder Zugaufforderung an die Clients gesendet wird. Das Spielstatus-Tag ist dabei noch in einem _data_-Tag der Klasse _memento_ gewrappt:

[[memento]]
=== memento

* `ROOM_ID` Id des GameRooms
* `STATUS` Gamestate wie in xref:status[]

[source,xml]
----
<room roomId="ROOM_ID">
  <data class="memento">
    STATUS
  </data>
</room>
----

[[status]]
=== Status

* `I` Nummer der Farbe, die aktuell an der Reihe ist (1=BLUE, 2=YELLO, 3=RED, 4=GREEN)
* `Z` aktuelle Zugzahl
* `R` aktuelle Rundenzahl
* `P` Spielstein, der in der ersten Runde gelegt werden muss, siehe xref:spielsteine[]
* `T` Team, welches beginnt (`ONE`, `TWO`)
* `board` Das Spielbrett, wie in xref:spielbrett[] definiert
* `blueShapes`, `yellowShapes`, `redShapes`, `greenShapes` Noch nicht gesetzte Spielsteine, siehe xref:undeployed[]
* `orderedColors` Die Farben in ihrer Zugreihenfolge. Dies beinhaltet nur Farben, die noch im Spiel sind.
* `first` Name und auch Team des ersten Spielers.
* `second` Name und auch Team des zweiten Spielers.
* `lastMove` der zuletzt ausgeführte Zug, siehe xref:last-move[]
* `startColor` Die Farbe die zuerst gespielt wird.

[source,xml]
----
<state class="state" currentColorIndex="I" turn="Z" round="R" startPiece="P">
  <startTeam class="team">T</startTeam>
  board
  blueShapes
  yellowShapes
  redShapes
  greenShapes
  orderedColors
  first
  second
  lastMove
  startColor
</state>
----

[[spielbrett]]
=== Spielbrett

* `X` X-Koordinate
* `Y` Y-Koordinate
* `CONTENT` Farbe des Spielsteins, der dieses Feld überdeckt (`BLUE`,`YELLOW`,`RED`,`GREEN`)

[source,xml]
----
<board>
  <fields>
    <field x="17" y="0" content="BLUE"/>
    ...
    <field x="17" y="2" content="BLUE"/>
  </fields>
  ...
  </board>
----

`<board>` enthaelt `<field>` Tags für alle Felder, die bereits belegt sind.
Leere Felder kommen nicht vor. Grundsätzlich besteht das Spielbrett aber immer
aus 20x20 Feldern, wobei das Feld links oben die X- und Y-Koordinate 0 hat und
die positive X-Achste nach rechts und die positive Y-Achse nach unten verläuft.

[[undeployed]]
=== Nicht gesetzte Spielsteine

[source,xml]
----
<blueShapes class="linked-hash-set">
  <shape>MONO</shape>
  <shape>DOMINO</shape>
  <shape>TRIO_L</shape>
  <shape>TRIO_I</shape>
  <shape>TETRO_O</shape>
  <shape>TETRO_T</shape>
  <shape>TETRO_I</shape>
  <shape>TETRO_L</shape>
  <shape>TETRO_Z</shape>
  <shape>PENTO_L</shape>
  <shape>PENTO_T</shape>
  <shape>PENTO_S</shape>
  <shape>PENTO_Z</shape>
  <shape>PENTO_I</shape>
  <shape>PENTO_P</shape>
  <shape>PENTO_W</shape>
  <shape>PENTO_U</shape>
  <shape>PENTO_R</shape>
  <shape>PENTO_X</shape>
  <shape>PENTO_Y</shape>
</blueShapes>
----

Die nicht gesetzten Steine werden durch `<shape>` Tags in einem `<blueShapes>`, `<yellowShapes>`, `<redShapes>` und `<greenShapes>` Tag dargestellt.

[[last-move]]
=== Vorheriger Zug

[source,xml]
----
<lastMove class="sc.plugin2021.SetMove">
  <piece color="BLUE" kind="PENTO_V" rotation="RIGHT" isFlipped="false">
    <position x="17" y="0"/>
  </piece>
</lastMove>
----

Der vorherige Zug hat die selbe Struktur wie ein xref:zug[], der gesendet wird, ausser dass das Tag `<lastMove>` und nicht `<data>` heisst. Der vorherige Zug wird in jedem Spielstatus angegeben, ausser vor dem ersten Zug.

=== Beispiel kompletter Spielstatus

Hier ist das XML eines kompletten beispielhaften Spielstatus, wie es der Computerspieler vom Server bekommt:

[source,xml]
----
<room roomId="cb3bc426-5c70-48b9-9307-943bc328b503">
  <data class="memento">
    <state class="state" currentColorIndex="1" turn="1" round="1" startPiece="PENTO_V">
      <startTeam class="team">ONE</startTeam>
      <board>
        <field x="17" y="0" content="BLUE"/>
        <field x="18" y="0" content="BLUE"/>
        <field x="19" y="0" content="BLUE"/>
        <field x="17" y="1" content="BLUE"/>
        <field x="17" y="2" content="BLUE"/>
      </board>
      <blueShapes class="linked-hash-set">
        <shape>MONO</shape>
        <shape>DOMINO</shape>
        <shape>TRIO_L</shape>
        <shape>TRIO_I</shape>
        <shape>TETRO_O</shape>
        <shape>TETRO_T</shape>
        <shape>TETRO_I</shape>
        <shape>TETRO_L</shape>
        <shape>TETRO_Z</shape>
        <shape>PENTO_L</shape>
        <shape>PENTO_T</shape>
        <shape>PENTO_S</shape>
        <shape>PENTO_Z</shape>
        <shape>PENTO_I</shape>
        <shape>PENTO_P</shape>
        <shape>PENTO_W</shape>
        <shape>PENTO_U</shape>
        <shape>PENTO_R</shape>
        <shape>PENTO_X</shape>
        <shape>PENTO_Y</shape>
      </blueShapes>
      <yellowShapes class="linked-hash-set">
        <shape>MONO</shape>
        <shape>DOMINO</shape>
        <shape>TRIO_L</shape>
        <shape>TRIO_I</shape>
        <shape>TETRO_O</shape>
        <shape>TETRO_T</shape>
        <shape>TETRO_I</shape>
        <shape>TETRO_L</shape>
        <shape>TETRO_Z</shape>
        <shape>PENTO_L</shape>
        <shape>PENTO_T</shape>
        <shape>PENTO_V</shape>
        <shape>PENTO_S</shape>
        <shape>PENTO_Z</shape>
        <shape>PENTO_I</shape>
        <shape>PENTO_P</shape>
        <shape>PENTO_W</shape>
        <shape>PENTO_U</shape>
        <shape>PENTO_R</shape>
        <shape>PENTO_X</shape>
        <shape>PENTO_Y</shape>
      </yellowShapes>
      <redShapes class="linked-hash-set">
        <shape>MONO</shape>
        <shape>DOMINO</shape>
        <shape>TRIO_L</shape>
        <shape>TRIO_I</shape>
        <shape>TETRO_O</shape>
        <shape>TETRO_T</shape>
        <shape>TETRO_I</shape>
        <shape>TETRO_L</shape>
        <shape>TETRO_Z</shape>
        <shape>PENTO_L</shape>
        <shape>PENTO_T</shape>
        <shape>PENTO_V</shape>
        <shape>PENTO_S</shape>
        <shape>PENTO_Z</shape>
        <shape>PENTO_I</shape>
        <shape>PENTO_P</shape>
        <shape>PENTO_W</shape>
        <shape>PENTO_U</shape>
        <shape>PENTO_R</shape>
        <shape>PENTO_X</shape>
        <shape>PENTO_Y</shape>
      </redShapes>
      <greenShapes class="linked-hash-set">
        <shape>MONO</shape>
        <shape>DOMINO</shape>
        <shape>TRIO_L</shape>
        <shape>TRIO_I</shape>
        <shape>TETRO_O</shape>
        <shape>TETRO_T</shape>
        <shape>TETRO_I</shape>
        <shape>TETRO_L</shape>
        <shape>TETRO_Z</shape>
        <shape>PENTO_L</shape>
        <shape>PENTO_T</shape>
        <shape>PENTO_V</shape>
        <shape>PENTO_S</shape>
        <shape>PENTO_Z</shape>
        <shape>PENTO_I</shape>
        <shape>PENTO_P</shape>
        <shape>PENTO_W</shape>
        <shape>PENTO_U</shape>
        <shape>PENTO_R</shape>
        <shape>PENTO_X</shape>
        <shape>PENTO_Y</shape>
      </greenShapes>
      <lastMoveMono class="linked-hash-map"/>
      <orderedColors>
        <color>BLUE</color>
        <color>YELLOW</color>
        <color>RED</color>
        <color>GREEN</color>
      </orderedColors>
      <first displayName="One">
        <color class="team">ONE</color>
      </first>
      <second displayName="Two">
        <color class="team">TWO</color>
      </second>
      <lastMove class="sc.plugin2021.SetMove">
        <piece color="BLUE" kind="PENTO_V" rotation="RIGHT" isFlipped="false">
          <position x="17" y="0"/>
        </piece>
      </lastMove>
      <startColor>BLUE</startColor>
    </state>
  </data>
</room>
----
