== Spielstatus
Es folgt die Beschreibung des Spielstatus, der vor jeder Zugaufforderung an die Clients gesendet wird. Das Spielstatus-Tag ist dabei noch in einem _data_-Tag der Klasse _memento_ gewrappt:

[[memento]]
=== memento
--
* ROOM_ID Id des GameRooms
* STATUS Gamestate wie in xref:status[]
--
[source,xml]
----
<room roomId="ROOM_ID">
  <data class="memento">
    STATUS
  </data>
</room>
----

[[status]]
=== Status
--
* I Nummer der Farbe, die aktuell an der Reihe ist (1=BLUE, 2=YELLO, 3=RED, 4=GREEN)
* Z aktuelle Zugzahl
* R aktuelle Rundenzahl
* P Spielstein, der in der ersten Runde gelegt werden muss (siehe xref:spielsteine[]
* T Team, welches beginnt (ONE/TWO)
* board Das Spielbrett, wie in xref:spielbrett[] definiert
* blueShapes, yellowShapes, redShapes, greenShapes Noch nicht gesetzte Spielsteine, siehe xref:undeployed[]
* lastMove der zuletzt ausgeführte Zug, siehe xref:last-move[]
--
[source,xml]
----
<state class="state" currentColorIndex="I" turn="Z" round="R" startPiece="P">
  <startTeam class="team">T</startTeam>
  board
  blueShapes
  yellowShapes
  redShapes
  greenShapes
  lastMove
</state>
----

[[spielbrett]]
=== Spielbrett
--
* FIELD Ein Spielfeld wie in xref:spielfeld[] definiert.
--
[source,xml]
----
<board>
  <fields>
    <null/>
    ...
    <null/>
    <field x="-5" y="2" z="3" isObstructed="false"/>
    ...
    FIELD
    ...
    <field x="-5" y="5" z="0" isObstructed="false"/>
  </fields>
  ...
  </board>
----

`<board>` enthaelt 11 `<fields>` Tags die wiederrum 11 Eintraege haben. Das ganze repraesentiert ein 11x11 2D-Array. Da das Spielfeld aber nicht rechteckig ist sondern die Form eines Hexagons hat, sind nicht alle Array-Eintraege durch Felder belegt, sondern manche durch `<null/>`. Das Feld mit den X- und Y-Koordinaten `x` und `y` ist im Array an der Stelle (`x+5`, `y+5`) gespeichert.

[[spielfeld]]
=== Spielfeld
--
* X X-Koordinate
* Y Y-Koordinate
* Z Z-Koordinate
* OBSTRUCTED Blockiert (true) oder nicht (false)
* PIECES Spielsteine (falls auf dem Feld vorhanden). Oberster Spielstein kommt als letztes in der Liste. Siehe xref:spielstein[].
--
[source,xml]
----
<field x="X" y="Y" z="Z" isObstructed="OBSTRUCTED">
  PIECES
</field>
----

[[spielstein]]
=== Spielstein
--
* OWNER Farbe (RED/BLUE)
* TYPE Insektentyp (ANT, BEE, BEETLE, GRASSHOPPER, SPIDER)
--
[source,xml]
----
<piece owner="OWNER" type="TYPE"/>
----
[[undeployed]]
=== Nicht gesetzte Spielsteine

[source,xml]
----
<undeployedRedPieces>
  <piece owner="RED" type="BEE"/>
  ...
</undeployedRedPieces>
<undeployedBluePieces>
  <piece owner="BLUE" type="BEE"/>
  ...
</undeployedBluePieces>
----
