== Züge senden

[[der-move]]
=== Der Move
Der Move ist die Antwort auf den MoveRequest des Servers.

[[senden]]
==== Senden
Der Move ist der allgemeine Zug, der in verschiedenen Varianten gesendet werden kann.

--
`ROOM_ID`:: ID des GameRooms, aus dem `MoveRequest`.
`ZUG`:: Zug wie in xref:zug[]
--
[source,xml]
----
<room roomId="ROOM_ID">
  ZUG
</room>
----

[[zug]]
=== ZUG
--
`COLOR`:: Farbe des zu setzenden Spielsteines (`BLUE`,`YELLOW`,`RED`,`GREEN`)
`KIND`:: Typ des zu setzenden Spielsteines (siehe xref:spielsteine[])
`ROTATION` :: Drehung des Spielsteines (`NONE`,`RIGHT`,`MIRROR`,`LEFT`)
`FLIPPED` :: Ob der Spielstein umgedreht wurde (`true`,`false`)
`X`:: X-Koordinate des zu ziehenden Spielsteines oder des Zielfeldes
`Y`:: Y-Koordinate des zu ziehenden Spielsteines oder des Zielfeldes
--

Es gibt drei Arten von Zuegen. Entweder man setzt einen eigenen noch nicht gesetzten Stein auf ein Zielfeld:
[source,xml]
----
<data class="sc.plugin2021.SetMove">
  <piece color="COLOR" kind="KIND" rotation="ROTATION" isFlipped="FLIPPED">
    <position x="X" y="Y"/>
  </piece>
</data>
----

Oder man möchte nicht setzen, dann ist es erlaubt, auszusetzen:
[source,xml]
----
<data class="sc.plugin2021.SkipMove"/>
----


[[debughints]]
=== Debughints
Zügen können Debug-Informationen beigefügt werden:

[source,xml]
----
<hint content="S" />
----

Damit sieht beispielsweise ein Zug so aus:

[source,xml]
----
<room roomId="ROOM_ID">
  <data class="sc.plugin2021.SetMove">
    <piece color="COLOR" kind="KIND" rotation="ROTATION" isFlipped="FLIPPED">
      <position x="X" y="Y"/>
    </piece>
    <hint content="Dies ist ein Hint." />
    <hint content="noch ein Hint" />
  </data>
</room>
----
