:imagesdir: ./../images
:toc: right
:toc-title: Inhalt
:source-highlighter: pygments
:icons: font
:author: Simon Döring

= GameRuleLogic: Hilfreiche Hilfsfunktionen

Die Klasse GameRuleLogic hat viele Hilfsfunktionen, mit welchen man die Regeln des Spieles überprüfen kann. Hierbei sind alle Funktionen static. D.h., dass man sie ohne eine Instanz aufrufen kann.

|=======================
|static int|_calculateCarrots(int moveCount)_ +
Berechnet wie viele Karotten für einen Zug der Länge moveCount benötigt werden.
|static int    |_calculateMoveableFields(int carrots)_ +
Berechnet, wie weit man mit carrots Karotten gehen kann. Beispiel: Mit 68 Karotten kann man 11 Felder weit gehen.
|static boolean    |_canPlayCard(GameState state)*_ +
Gibt zurück, ob der derzeitige Spieler eine Karte spielen kann.
|static boolean    |_isValidToAdvance(GameState state, int distance)_ +
Überprüft _Advance_ Aktionen auf ihre Korrektheit. _Distance_ steht für die Distanz die man zurücklegen will.Three
|static boolean    |_isValidToEat(GameState state)_ +
Überprüft _EatSalad_ Züge auf Korrektheit. Diese Funktion bezieht sich *nicht* auf die Karte  _TAKE_OR_DROP_CARROTS_
|static boolean    |_isValidToExchangeCarrots(GameState state, int n)_ +
Überprüft ob der derzeitige Spieler 10 Karotten nehmen oder abgeben kann. „n“ kann entweder 10 oder -10 sein. Je nachdem ob man annehmen oder abgeben will. Diese Funktion bezieht sich *nicht* auf die Karte _EAT_SALAD_.
|static boolean    |_isValidToFallBack(GameState state)_ +
Überprüft _FallBack_ Züge auf Korrektheit
|static boolean    |_isValidToPlayCard(GameState state, CardType c,int n)*_ +
Überprüft ob der derzeitige Spieler die Karte spielen kann. „n“ wird für die _TAKE_OR_DROP_CARROTS_ Karte benötigt (s.u). „n“ kann die Wert 0, 20 oder -20 annehmen.
|static boolean    |_isValidToPlayEatSalad(GameState state)*_ +
Überprüft ob der derzeitige Spieler die _EAT_SALAD_ Karte spielen darf.
|static boolean    |_isValidToPlayFallBack(GameState state)*_ +
Überprüft ob der derzeitige Spieler die _FALL_BACK_ Karte spielen darf.
|static boolean    |_isValidToPlayHurryAhead(GameState state) *_ +
Überprüft ob der derzeitige Spieler die _HURRY_AHEAD_ Karte spielen darf.
|static boolean    |_isValidToPlayTakeOrDropCarrots(GameState state,int n)*_ +
Überprüft ob der derzeitige Spieler die _TAKE_OR_DROP_CARROTS_ Karte spielen darf. „n“ kann entweder 0, 20 oder -20 sein.
|static boolean   |_isValidToSkip(GameState state)_ +
Überprüft, ob der derzeitige Spieler aussetzen darf.
|static boolean    |_mustEatSalad(GameState state)_ +
Überprüft ob man einen Salat fressen muss. Dies ist immer der Fall, wenn man in der vorherigen Runde ein Salatfeld betreten hat.
|static boolean    |_mustPlayCard(GameState state) *_ +
Überprüft ob eine Karte gespielt werden muss.
|static boolean    |_playerMustAdvance(GameState state)_ +
Überprüft ab der derzeitige Spieler im nächsten Zug einen Vorwärtszug machen muss.
|=======================
*Diese Funktionen werden im Kapitel „Erweiterte Beispiele“ besprochen.

TIP: Die komplette API-Dokumentation ist in doc/sc/plugin2018/util/GameRuleLogic.html zu finden.

== Simulation des Gegners

Natürlich kann man alle diese Funktionen auch auf den Gegenspieler anwenden. Dafür müssen wir allerdings eine Kopie des GameState erstellen:

[source, java]
------
try {
	GameState otherGameState = gameState.clone();//Deep-Copy
	otherGameState.setTurn(gameState.getTurn()+1); //Rundenanzahl hochsetzten für switch Befehl
	otherGameState.switchCurrentPlayer(); //Tausche currentPlayer (hängt von der Rundenanzahl ab)
	//Gib Informationen über den Gegner aus
	System.out.println("CurrentPlayer von otherGameState:" + otherGameState.getCurrentPlayer());
} catch (CloneNotSupportedException e1) {// Fehlerbehandlung
	e1.printStackTrace();
}
------

Alle Funktionen von GameRuleLogic können wir nun, mithilfe der Variable otherGameState, auf den Gegner anwenden.

== Einführende Beispiele

Die meisten Funktionen dieser Klasse sind selbsterklärend. Dennoch werden einige der häufig verwendeten Funktionen mit kleinen Beispielen vorgestellt.

[source, java]
------
if(GameRuleLogic.isValidToEat(gameState) != GameRuleLogic.mustEatSalad(gameState)){
	System.out.println("Unmöglich");
}
------

Nach den Regeln muss man immer ein Salat essen, wenn man im vorherigen Zug ein Salatfeld betreten hat. Außerdem ist dies die einzige Möglichkeit die Aktion EatSalad auszuführen (nicht mit dem Spielen der EAT_SALAD Karte verwechseln).

Dadurch wird auch die Unerfüllbarkeit des folgenden Ausdrucks impliziert:

[source, java]
------
if(GameRuleLogic.isValidToEat(gameState) && (GameRuleLogic.isValidToFallBack(gameState) || GameRuleLogic.canMove(gameState))){
	System.out.println("Unmöglich");
}
------

Eine weiter hilfreiche Funktion ist _isValidToAdvance_. Mit dieser Funktion wird überprüft, ob ein Vorwärtszug mit der übergeben Distanz überhaupt möglich ist:

[source, java]
------
if(GameRuleLogic.isValidToAdvance(gameState, GameRuleLogic.calculateMoveableFields(currentPlayer.getCarrots())+1)){
	System.out.println("Unmöglich");
}
------

Die Funktion _calculateMoveableFields_ gibt hierbei die maximale Entfernung zurück, welche man mit den übergebenen Karotten laufen darf. Diese maximale Entfernung wird immer um 1 erhöht, was dazu führt, dass der Zug immer unmöglich ist.

== Erweitertes Beispiel

Alle Funktionen die mit einem * markiert wurden (s.o) haben eine Gemeinsamkeit. Sie beziehen sich auf das Spielen von Karten. Das Spielen von Karten ist allerdings nur erlaubt, wenn man das entsprechende Hasenfeld in der selben Zug betreten hat. Deshalb müssen wir GameState bearbeiten, damit diese Funktionen überhaupt Sinn haben. Das folgende Beispiel gibt eine Möglichkeit an, wie man diese Funktionen einsetzten kann:

[source, java]
------
if(gameState.getNextFieldByType(FieldType.HARE, currentPlayer.getFieldIndex())>0){//wenn es ein nächstes Hasenfeld gibt
try {

	GameState gameHare = gameState.clone(); //erstelle Deep-Copy
	//setzte den aktuellen Spieler auf ein Hasenfeld
	gameHare.getCurrentPlayer().setFieldIndex(gameState.getNextFieldByType(FieldType.HARE, currentPlayer.getFieldIndex()));
	System.out.println(gameHare.getCurrentPlayer().getCards()); //gib alle Karten aus

	//Welche Karten kann man spielen?
	System.out.println("Play EatSalad: " + GameRuleLogic.isValidToPlayEatSalad(gameHare));
	System.out.println("Play TakeOrDropCarrots: " + GameRuleLogic.isValidToPlayTakeOrDropCarrots(gameHare,20));
	System.out.println("Play HurryAhead: " + GameRuleLogic.isValidToPlayHurryAhead(gameHare));
	System.out.println("Play FallBack: " + GameRuleLogic.isValidToPlayFallBack(gameHare));
} catch (CloneNotSupportedException e1) {
	e1.printStackTrace();
}
}//ende if
------

Hierfür müssen wir den Spieler einfach nur auf das Hasenfeld setzten. Allerdings wird nicht überprüft, ob der Spieler überhaupt bis zum nächsten Hasenfeld laufen kann.

== Aufgaben

. Ist das Ausführen der inneren If-Bedingung wirklich unmöglich. Erkläre warum oder gib ein Gegenbeispiel an:

[source, java]
------
int dif = gameState.getOtherPlayer().getFieldIndex() - gameState.getCurrentPlayer().getFieldIndex();

if(dif >= 0 && dif <= GameRuleLogic.calculateMoveableFields(currentPlayer.getCarrots())){
	if(GameRuleLogic.isValidToAdvance(gameState, dif)){
		System.out.println("Unmöglich");
	}
}
------

[start = 2]
. Erweiterte das Beispiel aus dem Kapitel „Erweitertes Beispiel“ so, dass sicher gestellt wird, dass der aktuelle Spieler auf ein Hasenfeld gesetzt wird, welches er wirklich erreichen kann.
