== Die richtige Programmiersprache

Am einfachsten ist es natürlich den Java Simple-Client als Basis zu nutzen, allerdings könnt ihr auch eigene Clients in anderen Sprachen schreiben. Das ist mit mehr Arbeit verbunden, aber wenn ihr eine Sprache kennt, die ihr gerne nutzt, oder die andere Vorteile besitzt, dann kann es sich lohnen!

Wenn ihr also genug Erfahrung habt und euch entscheidet den schwereren Weg zu gehen, dann solltet ihr euch die https://cau-kiel-tech-inf.github.io/socha-enduser-docs/spiele/piranhas/xml-dokumentation.html[XML-Dokumentation] genau anschauen, da ihr die ganze Kommunikation, sowie das Parsen der XML Nachrichten, implementerien müsst. Außerdem empfehle ich euch als Beispiel den (inoffiziellen) https://github.com/matthesjh/sc19-swift-client[Swift Client] anzusehen, dafür müsst ihr auch nicht Swift können. Wenn ihr eine andere prozedurale Programmiersprache kennt, dann werdet ihr gut genug verstehen was der Client macht um es in eurer Sprache nachzubauen. Auf ähnliche Weise können natürlich auch https://github.com/CAU-Kiel-Tech-Inf/socha[der Java Client source code] und https://github.com/niklasCarstensen/SoftwareChallengeCsharpClient[der C# Client source code] helfen. 

Am besten sprecht ihr die Verwendung einer anderen Programmiersprache frühzeitig mit eurem Tutor ab, 
damit sichergestellt ist, dass der Computerspieler auch am
Wettkampf teilnehmen kann. Wir stellen gern eine passende Laufzeitumgebung auf
dem Wettkampfsystem für die Programmiersprache zur Verfügung.
