== Spiel betreten
Wenn begonnen wird mit dem Server zu kommunizieren, muss zuallererst 

[source,xml]
----
<protocol> 
----
gesendet werden, um die Kommunikation zu beginnen.

[[ohne-reservierung]]
=== Ohne Reservierung
Betritt ein beliebiges offenes Spiel:

[source,xml]
----
<join gameType="swc_2018_hase_und_igel"/>
----
Sollte kein Spiel offen sein, wird so ein neues erstellt.
Der Server antwortet darauf mit:

--
* ROOM_ID Id des GameRooms
--
[source,xml]
----
<joined roomId="ROOM_ID"/>
----

Alle administrativen Clients werden ebenfalls darüber benachrichtigt und erhalten folgende Nachricht:

--
* ROOM_ID Id des GameRooms
--
[source,xml]
----
<joinedGameRoom roomId="ROOM_ID" existing="false"/>
----

Falls bereits ein GameRoom offen war, ist dementsprechend existing true.

[[mit-reservierungscode]]
=== Mit Reservierungscode
Ist ein Reservierungscode gegeben, so kann man den durch den Code gegebenen Platz betreten.

[[join-reserved]]
==== Join mit RC

--
* RC Reservierungscode
--
[source,xml]
----
<joinPrepared reservationCode="RC"/>
----

[[welcome-message]]
==== Welcome Message
Der Server antwortet darauf nur, wenn der zweite Client ebenfalls verbunden ist:

--
* ROOM_ID Id des GameRooms
* COLOR Spielerfarbe also red oder blue
* status GameState wie in xref:status[]
--
[source,xml]
----
<joined roomId="ROOM_ID"/>
<room roomId="ROOM_ID">
  <data class="welcomeMessage" color="COLOR"></data>
</room>
<room roomId="ROOM_ID">
  <data class="memento">
  	status
  </data>
</room>
----


